meta_product_name: "Expify"
meta_title: "Expify - Find Gigs, Get EXP"
meta_description: "Connecting recent grads to short internships and gigs at multiple European startups, while gamifying the results (with EXP!)"
meta_image: "cover.png"
twitter_account: "@nouwasy"   # required for Twitter Cards
